/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    // the Spring Boot plugin (brings in dependency‑management too)
    id("org.springframework.boot") version "3.4.5"
    // lets you omit versions on Spring dependencies
    id("io.spring.dependency-management") version "1.1.7"
}

group = "com.clashbot"
version = "1.0"

val jdaVersion = "3.2.8" // 

repositories {
    // look in the local libs folder first
    flatDir {
        dirs("libs")
    }
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("com.discord4j:discord4j-core:$jdaVersion")    
    implementation("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    implementation("com.squareup.okhttp3:okhttp:4.10.0")
    implementation(files("libs/clashbot-model-0.0.2-SNAPSHOT.jar"))

    /*
     * Current release of lycoon/clash-api has breaking issues with current API.
     * A pull request with a fix to this issue has been submitted, but in the mean
     * time a snapshot of the fixed version is being ustilized as a temporary solution.
     */
    // implementation("io.github.lycoon:clash-api:5.1.5") <- Broken
    implementation(files("libs/clash-api-5.1.5.jar"))

    // This dependency is used by the application.
    implementation(libs.guava)
}
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
